schema-version: v2
kind: plugin
metadata:
  name: robot-api-plugin
  display-name: robot-api-plugin
  description: Plugin para testes de API's com a Library Requests
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes.md
  requirements: docs/requirements.md
  single-use: False
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Python
  repository: https://github.com/allanocosta/robot-api-plugin.git
  stk-projects-only: false

  hooks:
    - type: run
      trigger: after-render
      commands:
        - pip install robotframework-requests